name: resuable_workflow

on:
  workflow_call:
    #secrets:
      #token: ${{ secrets.GIT_ACCESS_TOKEN }}
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    
    - name: Run a command
      run: echo "I am running the workflow and this workflow is resuable because I am using workflow_call"
      
    - name: Print token
      run: echo ${{ secrets.GIT_ACCESS_TOKEN }}
        

